<?php
namespace ResourceCatalog\Model;

interface IResourceCatalogTypeEnName
{
    const TYPE_ENNAME = array(
        IResourceCatalog::TYPE['NULL'] => '',
        IResourceCatalog::TYPE['XBXZCF'] => 'xbxzcf',
        IResourceCatalog::TYPE['XBXZXK'] => 'xbxzxk',
        IResourceCatalog::TYPE['JGJCDXZJL'] => 'jgjcdxzjl',
        IResourceCatalog::TYPE['SJJXMXX'] => 'sjjxmxx',
        IResourceCatalog::TYPE['QIYEJBXX'] => 'qiyejbxx',
        IResourceCatalog::TYPE['GTGSHXX'] => 'gtgshxx',
        IResourceCatalog::TYPE['CMQYSBXX'] => 'cmqysbxx',
        IResourceCatalog::TYPE['YPLSQYXX'] => 'yplsqyxx',
        IResourceCatalog::TYPE['JGRYXX'] => 'jgryxx',
        IResourceCatalog::TYPE['SXQYHMD'] => 'sxqyhmd',
        IResourceCatalog::TYPE['SPYPTSJBJLGR'] => 'spyptsjbjlgr',
        IResourceCatalog::TYPE['SPYPTSJBJLDW'] => 'spyptsjbjldw',
        IResourceCatalog::TYPE['HNMPCPXX'] => 'hnmpcpxx',
        IResourceCatalog::TYPE['QYYCMLXX'] => 'qyycmlxx',
        IResourceCatalog::TYPE['QYZXXX'] => 'qyzxxx',
        IResourceCatalog::TYPE['QYDXXX'] => 'qydxxx',
        IResourceCatalog::TYPE['CCJCJGXX'] => 'ccjcjgxx',
        IResourceCatalog::TYPE['FRXX'] => 'frxx',
        IResourceCatalog::TYPE['YSCRJZJJJZGRDXX'] => 'yscrjzjjjzgrdxx',
        IResourceCatalog::TYPE['JDCWFXX'] => 'jdcwfxx',
        IResourceCatalog::TYPE['JSZGXX'] => 'jszgxx',
        IResourceCatalog::TYPE['SJYXXS'] => 'sjyxxs',
        IResourceCatalog::TYPE['JYJGXINXI'] => 'jyjgxinxi',
        IResourceCatalog::TYPE['GRRYXXJYJ'] => 'grryxxjyj',
        IResourceCatalog::TYPE['JGRYXXSJYJ'] => 'jgryxxsjyj',
        IResourceCatalog::TYPE['ESCJDPGJGHZZS'] => 'escjdpgjghzzs',
        IResourceCatalog::TYPE['ZYJNZSXX'] => 'zyjnzsxx',
        IResourceCatalog::TYPE['YLBXXX'] => 'ylbxxx',
        IResourceCatalog::TYPE['YZTQSBXXHMD'] => 'yztqsbxxhmd',
        IResourceCatalog::TYPE['SYBXXX'] => 'sybxxx',
        IResourceCatalog::TYPE['SBQYXX'] => 'sbqyxx',
        IResourceCatalog::TYPE['GZRYXX'] => 'gzryxx',
        IResourceCatalog::TYPE['YZTQNMGGZHMD'] => 'yztqnmggzhmd',
        IResourceCatalog::TYPE['SLYSXKZXX'] => 'slysxkzxx',
        IResourceCatalog::TYPE['GRRYXXJTJ'] => 'grryxxjtj',
        IResourceCatalog::TYPE['QYGSZXXX'] => 'qygszxxx',
        IResourceCatalog::TYPE['AJNSRXX'] => 'ajnsrxx',
        IResourceCatalog::TYPE['ZDSSWFAJXX'] => 'zdsswfajxx',
        IResourceCatalog::TYPE['QYDSXZCFXX'] => 'qydsxzcfxx',
        IResourceCatalog::TYPE['SHZZNJXX'] => 'shzznjxx',
        IResourceCatalog::TYPE['GRRYXXMZJ'] => 'grryxxmzj',
        IResourceCatalog::TYPE['MBFQYML'] => 'mbfqyml',
        IResourceCatalog::TYPE['SHTTDJXX'] => 'shttdjxx',
        IResourceCatalog::TYPE['SFJDJGCYRYZGXX'] => 'sfjdjgcyryzgxx',
        IResourceCatalog::TYPE['SFJDJGDJXX'] => 'sfjdjgdjxx',
        IResourceCatalog::TYPE['GZJGJBXX'] => 'gzjgjbxx',
        IResourceCatalog::TYPE['GZYXX'] => 'gzyxx',
        IResourceCatalog::TYPE['JCFLFWSXX'] => 'jcflfwsxx',
        IResourceCatalog::TYPE['JCFLFWGZZJBXX'] => 'jcflfwgzzjbxx',
        IResourceCatalog::TYPE['LSSWSXX'] => 'lsswsxx',
        IResourceCatalog::TYPE['LSZYZGZXX'] => 'lszyzgzxx',
        IResourceCatalog::TYPE['JGRYXXSSFJ'] => 'jgryxxssfj',
        IResourceCatalog::TYPE['SJQYJSZXRDXX'] => 'sjqyjszxrdxx',
        IResourceCatalog::TYPE['ZFCGDLJGXX'] => 'zfcgdljgxx',
        IResourceCatalog::TYPE['SLGCZBXX'] => 'slgczbxx',
        IResourceCatalog::TYPE['GJJLTQYRZXX'] => 'gjjltqyrzxx',
        IResourceCatalog::TYPE['DTJXJGRXX'] => 'dtjxjgrxx',
        IResourceCatalog::TYPE['TJDCDXML'] => 'tjdcdxml',
        IResourceCatalog::TYPE['HNSZLJDW'] => 'hnszljdw',
        IResourceCatalog::TYPE['XSPJXX'] => 'xspjxx',
        IResourceCatalog::TYPE['SXBZXJGXX'] => 'sxbzxjgxx',
        IResourceCatalog::TYPE['SXBZXRMD'] => 'sxbzxrmd',
        IResourceCatalog::TYPE['XZXKQYXX'] => 'xzxkqyxx',
        IResourceCatalog::TYPE['QSLHXJJTJL'] => 'qslhxjjtjl',
        IResourceCatalog::TYPE['SPFYSXK'] => 'spfysxk',
        IResourceCatalog::TYPE['FDCKFQYZZXX'] => 'fdckfqyzzxx',
        IResourceCatalog::TYPE['JGRYXXSFGJ'] => 'jgryxxsfgj',
        IResourceCatalog::TYPE['XYTXHMD'] => 'xytxhmd',
        IResourceCatalog::TYPE['SYDWJBXX'] => 'sydwjbxx',
        
        IResourceCatalog::TYPE['XZQZXX'] => 'xzqzxx',
        IResourceCatalog::TYPE['XZZSXX'] => 'xzzsxx',
        IResourceCatalog::TYPE['XZCJXX'] => 'xzcjxx',
        IResourceCatalog::TYPE['XZQRXX'] => 'xzqrxx',
        IResourceCatalog::TYPE['XZJFXX'] => 'xzjfxx',
        IResourceCatalog::TYPE['JDJCXX'] => 'jdjcxx',
        IResourceCatalog::TYPE['XZJLXX'] => 'xzjlxx',
        IResourceCatalog::TYPE['QTXZZFXX'] => 'qtxzzfxx',
        IResourceCatalog::TYPE['HEIMDXX'] => 'heimdxx',
        IResourceCatalog::TYPE['HONGMDXX'] => 'hongmdxx',
        IResourceCatalog::TYPE['HYFJFLJG'] => 'hyfjfljg',

        IResourceCatalog::TYPE['QYHYSJ'] => 'qyhysj',

        IResourceCatalog::TYPE['TEST'] => 'test',
        IResourceCatalog::TYPE['DWYSZCXX'] => 'dwyszcxx',
        IResourceCatalog::TYPE['TQMYQYZK'] => 'tqmyqyzk',

        IResourceCatalog::TYPE['ZFCGHT'] => 'zfcght',
        IResourceCatalog::TYPE['GGZYJYHT'] => 'ggzyjyht',
        IResourceCatalog::TYPE['GQCGHT'] => 'gqcght',
        IResourceCatalog::TYPE['GCJSHT'] => 'gcjsht',
        IResourceCatalog::TYPE['QTHT'] => 'qtht',
        //@position
    );
}
