<?php

namespace ResourceCatalog\Model;

interface IResourceCatalogSubjectCategory
{
    //自然人
    const RESOURCE_CATALOG_NATURAL_PERSON = [
        'SXBZXRMD' => 3,
        'SPYPTSJBJLGR' => 11,
        'JDCWFXX' => 20,
        'JSZGXX' => 21,
        'SJYXXS' => 22,
        'GRRYXXJYJ' => 24,
        'ZYJNZSXX' => 27,
        'YLBXXX' => 28,
        'SYBXXX' => 30,
        'GZRYXX' => 32,
        'GRRYXXJTJ' => 35,
        'GRRYXXMZJ' => 41,
        'MBFQYML' => 42,
        'SFJDJGCYRYZGXX' => 44,
        'GZYXX' => 47,
        'JCFLFWGZZJBXX' => 49,
        'LSZYZGZXX' => 51,
        'DTJXJGRXX' => 57,
        'XSPJXX' => 60,
        'XYTXHMD' => 68,
    ];
    // 企业
    const RESOURCE_CATALOG_ENTERPRISE = [
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'FRXX' => 4,
        'QIYEJBXX' => 5,
        'GTGSHXX' => 6,
        'CMQYSBXX' => 7,
        'YPLSQYXX' => 8,
        'JGRYXX' => 9,
        'SXQYHMD' => 10,
        'SPYPTSJBJLDW' => 12,
        'HNMPCPXX' => 13,
        'QYYCMLXX' => 14,
        'QYZXXX' => 15,
        'QYDXXX' => 16,
        'CCJCJGXX' => 17,
        'JGJCDXZJL' => 18,
        'YSCRJZJJJZGRDXX' => 19,
        'JYJGXINXI' => 23,
        'JGRYXXSJYJ' => 25,
        'ESCJDPGJGHZZS' => 26,
        'YZTQSBXXHMD' => 29,
        'SBQYXX' => 31,
        'YZTQNMGGZHMD' => 33,
        'SLYSXKZXX' => 34,
        'QYGSZXXX' => 36,
        'AJNSRXX' => 37,
        'ZDSSWFAJXX' => 38,
        'QYDSXZCFXX' => 39,
        'SHZZNJXX' => 40,
        'SHTTDJXX' => 43,
        'SFJDJGDJXX' => 45,
        'GZJGJBXX' => 46,
        'JCFLFWSXX' => 48,
        'LSSWSXX' => 50,
        'JGRYXXSSFJ' => 52,
        'SJQYJSZXRDXX' => 53,
        'ZFCGDLJGXX' => 54,
        'SLGCZBXX' => 55,
        'GJJLTQYRZXX' => 56,
        'TJDCDXML' => 58,
        'HNSZLJDW' => 59,
        'SXBZXJGXX' => 61,
        'SJJXMXX' => 62,
        'XZXKQYXX' => 63,
        'QSLHXJJTJL' => 64,
        'SPFYSXK' => 65,
        'FDCKFQYZZXX' => 66,
        'JGRYXXSFGJ' => 67,
        'SYDWJBXX' => 69,
        'XZQZXX' => 70,
        'XZZSXX' => 71,
        'XZCJXX' => 72,
        'XZQRXX' => 73,
        'XZJFXX' => 74,
        'JDJCXX' => 75,
        'XZJLXX' => 76,
        'QTXZZFXX' => 77,
        'HEIMDXX' => 78,
        'HONGMDXX' => 79,
        'HYFJFLJG' => 80,
        'QYHYSJ' => 81,
        'DWYSZCXX' => 82,
        'TQMYQYZK'=>83,
        'ZFCGHT'=>84,
        'GGZYJYHT'=>85,
        'GQCGHT'=>86,
        'GCJSHT'=>87,
        'QTHT'=>88,
        'CCJCJG'=>89,
        'XYSFSQ'=>90,
        'QYFRGGXYZHPJJG' => 91,
    ];
}
