<?php
namespace ResourceCatalog\Model;

interface IResourceCatalog extends IResourceCatalogTypeName, IResourceCatalogTypeIdentify, IResourceCatalogTypeEnName, IResourceCatalogTypeDoublePublicity, IResourceCatalogTypeRedBlackList, IResourceCatalogIsConfirm
{
    const TYPE = array(
        'NULL' => 0,
        'XBXZCF' => 1,
        'XBXZXK' => 2,
        'SXBZXRMD' => 3,
        'FRXX' => 4,
        'QIYEJBXX' => 5,
        'GTGSHXX' => 6,
        'CMQYSBXX' => 7,
        'YPLSQYXX' => 8,
        'JGRYXX' => 9,
        'SXQYHMD' =>10,
        'SPYPTSJBJLGR' => 11,
        'SPYPTSJBJLDW' => 12,
        'HNMPCPXX' => 13,
        'QYYCMLXX' => 14,
        'QYZXXX' => 15,
        'QYDXXX' => 16,
        'CCJCJGXX' => 17,
        'JGJCDXZJL' => 18,
        'YSCRJZJJJZGRDXX' => 19,
        'JDCWFXX' => 20,
        'JSZGXX' => 21,
        'SJYXXS' => 22,
        'JYJGXINXI' => 23,
        'GRRYXXJYJ' => 24,
        'JGRYXXSJYJ' => 25,
        'ESCJDPGJGHZZS' => 26,
        'ZYJNZSXX' => 27,
        'YLBXXX' => 28,
        'YZTQSBXXHMD' => 29,
        'SYBXXX' => 30,
        'SBQYXX' => 31,
        'GZRYXX' => 32,
        'YZTQNMGGZHMD' => 33,
        'SLYSXKZXX' => 34,
        'GRRYXXJTJ' => 35,
        'QYGSZXXX' => 36,
        'AJNSRXX' => 37,
        'ZDSSWFAJXX' => 38,
        'QYDSXZCFXX' => 39,
        'SHZZNJXX' => 40,
        'GRRYXXMZJ' => 41,
        'MBFQYML' => 42,
        'SHTTDJXX' => 43,
        'SFJDJGCYRYZGXX' => 44,
        'SFJDJGDJXX' => 45,
        'GZJGJBXX' => 46,
        'GZYXX' => 47,
        'JCFLFWSXX' => 48,
        'JCFLFWGZZJBXX' => 49,
        'LSSWSXX' => 50,
        'LSZYZGZXX' => 51,
        'JGRYXXSSFJ' => 52,
        'SJQYJSZXRDXX' => 53,
        'ZFCGDLJGXX' => 54,
        'SLGCZBXX' => 55,
        'GJJLTQYRZXX' => 56,
        'DTJXJGRXX' => 57,
        'TJDCDXML' => 58,
        'HNSZLJDW' => 59,
        'XSPJXX' => 60,
        'SXBZXJGXX' => 61,
        'SJJXMXX' => 62,
        'XZXKQYXX' => 63,
        'QSLHXJJTJL' => 64,
        'SPFYSXK' => 65,
        'FDCKFQYZZXX' => 66,
        'JGRYXXSFGJ' => 67,
        'XYTXHMD' => 68,
        'SYDWJBXX'=>69,
        'XZQZXX' => 70,
        'XZZSXX' => 71,
        'XZCJXX' => 72,
        'XZQRXX' => 73,
        'XZJFXX' => 74,
        'JDJCXX' => 75,
        'XZJLXX' => 76,
        'QTXZZFXX' => 77,
        'HEIMDXX' => 78,
        'HONGMDXX' => 79,
        'HYFJFLJG' => 80,
        'QYHYSJ' => 81,
        'DWYSZCXX'=>82,
        'TQMYQYZK'=>83,
        'ZFCGHT'=>84,
        'GGZYJYHT'=>85,
        'GQCGHT'=>86,
        'GCJSHT'=>87,
        'QTHT'=>88,
        'CCJCJG'=>89,
        'XYSFSQ'=>90,
        'QYFRGGXYZHPJJG' => 91,
        //@position_type_92
        'TEST' => 500
    );

    const USERGROUP_TYPE_RELATIONSHIP = array(
        IUserGroup::ID['NULL'] => array(
            self::TYPE['NULL'],
            self::TYPE['XBXZCF'],
            self::TYPE['XBXZXK'],
            self::TYPE['CCJCJG'],
        ),
        IUserGroup::ID['FGW'] => array(
            self::TYPE['JGJCDXZJL'],
            self::TYPE['SJJXMXX'],
            self::TYPE['SYDWJBXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
            self::TYPE['TEST'],
            self::TYPE['QYFRGGXYZHPJJG'],
        ),
        IUserGroup::ID['XCZJ'] => array(
            self::TYPE['ZFCGDLJGXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XGAJ'] => array(
            self::TYPE['YSCRJZJJJZGRDXX'],
            self::TYPE['JDCWFXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSFJ'] => array(
            self::TYPE['SFJDJGCYRYZGXX'],
            self::TYPE['SFJDJGDJXX'],
            self::TYPE['GZJGJBXX'],
            self::TYPE['GZYXX'],
            self::TYPE['JCFLFWSXX'],
            self::TYPE['JCFLFWGZZJBXX'],
            self::TYPE['LSSWSXX'],
            self::TYPE['LSZYZGZXX'],
            self::TYPE['JGRYXXSSFJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XNYNCJ'] => array(
            self::TYPE['GJJLTQYRZXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSLJ'] => array(
            self::TYPE['SLGCZBXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XSTJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XXZSPJ'] => array(),
        IUserGroup::ID['XRSJ'] => array(
            self::TYPE['ZYJNZSXX'],
            self::TYPE['YLBXXX'],
            self::TYPE['YZTQSBXXHMD'],
            self::TYPE['SYBXXX'],
            self::TYPE['SBQYXX'],
            self::TYPE['GZRYXX'],
            self::TYPE['YZTQNMGGZHMD'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XJTJ'] => array(
            self::TYPE['SLYSXKZXX'],
            self::TYPE['GRRYXXJTJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XMZJ'] => array(
            self::TYPE['SHZZNJXX'],
            self::TYPE['GRRYXXMZJ'],
            self::TYPE['MBFQYML'],
            self::TYPE['SHTTDJXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XGXJ'] => array(
            self::TYPE['SJQYJSZXRDXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
            self::TYPE['TQMYQYZK'],
        ),
        IUserGroup::ID['XJYTYJ'] => array(
            self::TYPE['JSZGXX'],
            self::TYPE['SJYXXS'],
            self::TYPE['JYJGXINXI'],
            self::TYPE['GRRYXXJYJ'],
            self::TYPE['JGRYXXSJYJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XZFBGS'] => array(),
        IUserGroup::ID['XWJW'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ']
        ),
        IUserGroup::ID['XZJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XWLJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XXFJ'] => array(),
        IUserGroup::ID['XSJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ']
        ),
        IUserGroup::ID['XSCJGJ'] => array(
            self::TYPE['QIYEJBXX'],
            self::TYPE['GTGSHXX'],
            self::TYPE['CMQYSBXX'],
            self::TYPE['YPLSQYXX'],
            self::TYPE['JGRYXX'],
            self::TYPE['SXQYHMD'],
            self::TYPE['SPYPTSJBJLGR'],
            self::TYPE['SPYPTSJBJLDW'],
            self::TYPE['HNMPCPXX'],
            self::TYPE['QYYCMLXX'],
            self::TYPE['QYZXXX'],
            self::TYPE['QYDXXX'],
            self::TYPE['CCJCJGXX'],
            self::TYPE['FRXX'],
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XYJJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XXCZXJ'] => array(),
        IUserGroup::ID['XTYJRJ'] => array(),
        IUserGroup::ID['XTJJ'] => array(),
        IUserGroup::ID['XYBJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        ),
        IUserGroup::ID['XZRZYJ'] => array(
            self::TYPE['HEIMDXX'],
            self::TYPE['HONGMDXX'],
            self::TYPE['HYFJFLJG'],
            self::TYPE['XYTXHMD'],
            self::TYPE['XZQZXX'],
            self::TYPE['XZZSXX'],
            self::TYPE['XZCJXX'],
            self::TYPE['XZQRXX'],
            self::TYPE['XZJFXX'],
            self::TYPE['JDJCXX'],
            self::TYPE['XZJLXX'],
            self::TYPE['QTXZZFXX'],
            self::TYPE['QYHYSJ'],
        )
    );

    const STATUS_NORMAL = 0;

    const STATUS_DELETE = -2;
}
