<?php
namespace ResourceCatalog\Model;

interface IUserGroup extends IUserGroupIdentify
{
    const ID = array(
        'NULL' => 0,
        'FGW' => 1,
        'XCZJ' => 2,
        'XGAJ' => 3,
        'XSFJ' => 4,
        'XNYNCJ' => 5,
        'XSLJ' => 6,
        'XSTJ' => 7,
        'XXZSPJ' => 8,
        'XRSJ' => 9,
        'XJTJ' => 10,
        'XMZJ' => 11,
        'XGXJ' => 12,
        'XJYTYJ' => 13,
        'XZFBGS' => 14,
        'XWJW' => 15,
        'XZJJ' => 16,
        'XWLJ' => 17,
        'XXFJ' => 18,
        'XSJJ' => 19,
        'XSCJGJ' => 20,
        'XYJJ' => 21,
        'XXCZXJ' => 22,
        'XTYJRJ' => 23,
        'XTJJ' => 24,
        'XYBJ' => 25,
        'XZRZYJ' => 26,
        'LQZRMZF' => 27,
        'LCZRMZF' => 28,
        'XSZRMZF' => 29,
        'YDZRMZF' => 30,
        'XGZRMZF' => 31,
        'LJXRMZF' => 32,
        'PGXRMZF' => 33,
        'CJYXRMZF' => 34,
        'HHXRMZF' => 35,
        'BZWYBGS' => 36,
        'LYJ' => 37,
        'JBYFJKZX' => 38,
        'GAJJTJCDD' => 39,
    );
}
