<?php
namespace ResourceCatalog\Model;

interface IUserGroupIdentify
{
    const IDENTIFY = array(
        IUserGroup::ID['NULL'] => 'NULL',
        IUserGroup::ID['FGW'] => 'FGW',
        IUserGroup::ID['XCZJ'] => 'XCZJ',
        IUserGroup::ID['XGAJ'] => 'XGAJ',
        IUserGroup::ID['XSFJ'] => 'XSFJ',
        IUserGroup::ID['XNYNCJ'] => 'XNYNCJ',
        IUserGroup::ID['XSLJ'] => 'XSLJ',
        IUserGroup::ID['XSTJ'] => 'XSTJ',
        IUserGroup::ID['XXZSPJ'] => 'XXZSPJ',
        IUserGroup::ID['XRSJ'] => 'XRSJ',
        IUserGroup::ID['XJTJ'] => 'XJTJ',
        IUserGroup::ID['XMZJ'] => 'XMZJ',
        IUserGroup::ID['XGXJ'] => 'XGXJ',
        IUserGroup::ID['XJYTYJ'] => 'XJYTYJ',
        IUserGroup::ID['XZFBGS'] => 'XZFBGS',
        IUserGroup::ID['XWJW'] => 'XWJW',
        IUserGroup::ID['XZJJ'] => 'XZJJ',
        IUserGroup::ID['XWLJ'] => 'XWLJ',
        IUserGroup::ID['XXFJ'] => 'XXFJ',
        IUserGroup::ID['XSJJ'] => 'XSJJ',
        IUserGroup::ID['XSCJGJ'] => 'XSCJGJ',
        IUserGroup::ID['XYJJ'] => 'XYJJ',
        IUserGroup::ID['XXCZXJ'] => 'XXCZXJ',
        IUserGroup::ID['XTYJRJ'] => 'XTYJRJ',
        IUserGroup::ID['XFGZX'] => 'XFGZX',
        IUserGroup::ID['XYBJ'] => 'XYBJ',
        IUserGroup::ID['XZRZYJ'] => 'XZRZYJ',
        IUserGroup::ID['XZRZYJ'] => 'XZRZYJ',
        IUserGroup::ID['LQZRMZF'] => 'LQZRMZF',
        IUserGroup::ID['LCZRMZF'] => 'LCZRMZF',
        IUserGroup::ID['XSZRMZF'] => 'XSZRMZF',
        IUserGroup::ID['YDZRMZF'] => 'YDZRMZF',
        IUserGroup::ID['XGZRMZF'] => 'XGZRMZF',
        IUserGroup::ID['LJXRMZF'] => 'LJXRMZF',
        IUserGroup::ID['PGXRMZF'] => 'PGXRMZF',
        IUserGroup::ID['CJYXRMZF'] => 'CJYXRMZF',
        IUserGroup::ID['HHXRMZF'] => 'HHXRMZF',
    );
}
